name: Build Containers

on:
  ## Triggers the workflow on push or pull request events for everything
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  ## Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  ## Run on a schedule to get monthly updates
  schedule:
    - cron: "* * 29 * *"

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  ## Separate builds for each container
  ubuntu_18-04_stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ubuntu 18.04 Stock Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu18.04-stock
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu18.04-stock

      - name: Build and Push Ubuntu 18.04 Stock Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu18.04-stock
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu18.04-stock

  ubuntu_18-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Ubuntu 18.04 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu18.04
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu18.04

      - name: Build and Push Ubuntu 18.04 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu18.04
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu18.04


  ubuntu_20-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ubuntu 20.04 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu20.04
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu20.04

      - name: Build and Push Ubuntu 20.04 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu20.04
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu20.04

  ubuntu_22-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ubuntu 22.04 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu22.04
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu22.04

      - name: Build and Push Ubuntu 22.04 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu22.04
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:ubuntu22.04

  fedora_33:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Fedora 33 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora33
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora33

      - name: Build and Push Fedora 33 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora33
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora33

  fedora_34:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Fedora 34 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora34
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora34

      - name: Build and Push Fedora 34 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora34
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora34

  fedora_35:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}                
          username: ${{ env.REPO_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Fedora 32 Container
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora35
          push: false
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora35

      - name: Build and Push Fedora 32 Container
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora35
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/deps:fedora35
